scripts for database creation(drop) with test data
Social-projects-Rivne/rv-027py pull request #1
Opened 2017-10-25 21:44 UTC by NewIvanIvanov

2017-10-26 08:58 UTC, Michaluch requested changes

2017-10-26 08:58 UTC, Michaluch commented on createDB.py
> +class Attachment(db.Model):
please move each class in separate file

2017-10-27 19:03 UTC, andrewRv commented on models.py
> +    __tablename__ = 'Category'
Table name in lowercase

2017-10-27 19:12 UTC, andrewRv commented on models.py
> +    role_id = db.Column(db.ForeignKey(u'Roles.id'), index=True)
Add cascade deleting

2017-10-27 21:15 UTC, NewIvanIvanov commented on createDB.py
> +class Attachment(db.Model):
move classes into seperate file

2017-10-27 21:15 UTC, NewIvanIvanov commented on models.py
> +    __tablename__ = 'Category'
rename tables in lowercase

2017-10-27 21:22 UTC, NewIvanIvanov commented on models.py
> +    role_id = db.Column(db.ForeignKey(u'Roles.id'), index=True)
not sure about that. need to discuss

2017-10-29 22:45 UTC, closed without merging