Sorting Users  with develop
Social-projects-Rivne/rv-027py pull request #12
Opened 2017-11-04 18:23 UTC by Oksana098

2017-11-04 20:05 UTC, serge30 requested changes
Be aware that this PR conflicts with @KostSvitlana PR #11. 

Guys, you'd better discuss solution internally, because last of you merge PR will have to re-work it to be compatible.

2017-11-04 20:05 UTC, serge30 commented on backend/templates/user_page.html
> +    <form action="{{ url_for('user_page') }}" method="POST">
Using POST for sorting will make problems when user whats to reload a page in browser. In that case browser will ask for confirmation to re-send form and it might be confusing for user. GET here is the best option.

Anyway I'm not happy with solution to use forms with checkboxes here. I'd rather make all columns links to `user_page` route with `order_by` param, and handle this param in the router. But it's up to you.

2017-11-04 20:05 UTC, serge30 commented on backend/views/views.py
> +        print 'get'
I'm not sure it's needed here.

2017-11-04 20:05 UTC, serge30 commented on backend/views/views.py
> +        print 'post'
The same as above.

2017-11-04 20:05 UTC, serge30 commented on backend/views/views.py
> +                .order_by(User.role_id).all()
You have here too many duplicated code. It easily can be re-written to something like:
```
sort_fields = []
if 'delete_date_checkbox' in data:
    sort_fields.append(User.delete_date)
if 'role_checkbox' in data:
    sort_fields.append(User.role_id)
users = db.session.query(User, Role).filter(User.role_id == Role.id).order_by(*sort_fields).all()
```

2017-11-06 18:28 UTC, Oksana098 commented on backend/views/views.py
> +        print 'get'
fixed

2017-11-06 18:28 UTC, Oksana098 commented on backend/views/views.py
> +        print 'post'
fixed

2017-11-06 19:37 UTC, serge30 commented on backend/views/views.py
> +                .order_by(User.role_id).all()
Please address this comment too.

2017-11-07 17:29 UTC, closed without merging