Skeleton
Social-projects-Rivne/rv-027py pull request #6
Opened 2017-11-01 09:50 UTC by NewIvanIvanov

2017-11-01 14:12 UTC, serge30 requested changes

2017-11-01 14:12 UTC, serge30 commented on .gitignore
> -flask
`backend/config.py` is declared twice here

2017-11-01 14:12 UTC, serge30 commented on backend/config.py.example
> +    DEBUG = True
PEP8 recommends a blank line at the end of module.

2017-11-01 14:12 UTC, serge30 commented on backend/create_database.py
> +Insert test data into database.
Hmm, it doesn't look like valid Python statement.

2017-11-01 14:12 UTC, serge30 commented on backend/create_database.py
> +    database_exists
Please try to avoid using line ends escaping, preferred way is to use next syntax:
```
from sqlalchemy_utils.functions.database import (create_database,
                                                 database_exists)
```

2017-11-01 14:12 UTC, serge30 commented on backend/forms/forms.py
> +                                    and only letters, numbers and "_" may be used.""")
Triple quotes saves all control characters inside, so this line will have the next content:
```
Name must be between 3 and 32 chars 
                                    and only letters, numbers and "_" may be used.
```
What might be that you don't expect. 

Recommended syntax here is next:
```
Regexp(r"^[\w]{3,32}$", 
       message='Name must be between 3 and 32 chars '
               'and only letters, numbers and "_" may be used.')

2017-11-01 14:12 UTC, serge30 commented on backend/run.py
> +from manage import app
I believe this script is redundant, you may use `manage.py` script to run dev server.

2017-11-01 14:12 UTC, serge30 commented on backend/migrations.py
> +from manage import *
Please never use wildcard imports it leads to errors hard to find.

2017-11-01 14:12 UTC, serge30 commented on backend/manage.py
> +manager.add_command('db', MigrateCommand)
Looking through [Flask-Script's documentation](https://flask-script.readthedocs.io/en/latest/), I see it requires main section to work:
```
if __name__ == "__main__":
    manager.run()
```

2017-11-01 14:12 UTC, serge30 commented on backend/migrations.py
> +from manage import *
Please move the code of this script to `manage.py` and remove it.

2017-11-01 14:12 UTC, serge30 commented on backend/models/users.py
> +    def data_validataion(self):
Why do we need this validation when WTForms provides one?

2017-11-01 14:12 UTC, serge30 commented on backend/models/users.py
> +    def clear_form_data(self, data):
I'm not sure it's the right place for it. I'd rather put this code in controller module.

2017-11-01 14:12 UTC, serge30 commented on backend/static/js/main.js
> +'use strict';
Is this JS script used anywhere? I cannot find.

2017-11-01 14:12 UTC, serge30 commented on backend/templates/admin_page.html
> +			<a href="/user_page" class="btn btn-primary">Work with users</a>
'Users management' sounds better :)

2017-11-01 14:12 UTC, serge30 commented on backend/templates/base.html
> +<!DOCTYPE html>
Most likely that `bootstrap/base.html` already adds such HTML header. Please check.

2017-11-01 14:12 UTC, serge30 commented on backend/templates/login_page.html
> +</div>
Code to render flashed messages repeated almost in every template, so would be better to create some base template (e.g. `layout.html`) with such code and use it as base for all your templates.

2017-11-01 14:12 UTC, serge30 commented on backend/views/views.py
> +from models.users import Role, User
It is recommended to split imports in 3 groups and separate them by blank line:
1. Python standard library
2. Framework imports
3. Modules from your projects

So it will become:
```
from datetime import datetime

from flask import flash, render_template, redirect, request, session, url_for

from manage import app, db
from forms.forms import LoginForm, UserForm
from models.users import Role, User
```

2017-11-01 14:12 UTC, serge30 commented on requirements.txt
> +pep8==1.7.1
pep8 is not needed to run this project, so shouldn't be here.

2017-11-01 14:12 UTC, serge30 commented on backend/templates/user_page.html
> +							<td class="user_table-cell"><a href="/delete_user?id={{ user[0].id }}" class="btn btn-danger">Delete</a></td>
To generate URLs please use `url_for` function

2017-11-01 14:12 UTC, serge30 commented on backend/views/views.py
> +        User.role_id == Role.id).order_by(User.id).all()
SQLAlchemy supports another options for queries with JOINs: http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html#joined-eager-loading But no needs to fix this in scope of this PR, we will fix it later.

2017-11-01 14:12 UTC, serge30 commented on backend/views/views.py
> +                user.delete_date = form.delete_date.data
Consider using WTForm's [populate_obj](http://wtforms.readthedocs.io/en/latest/forms.html#wtforms.form.Form.populate_obj) method.

2017-11-01 14:12 UTC, serge30 commented on backend/views/views.py
> +                user = db.session.query(User).get(form.id.data)
You already have `user` variable populated in line 35.

2017-11-01 14:12 UTC, serge30 commented on backend/views/views.py
> +                User(**User().clear_form_data(form.data)).data_validataion()):
I'm not sure we need extra user's validation here, as WTForm is already used.

2017-11-01 14:12 UTC, serge30 commented on backend/static/css/style.css
> +.button {
Please review this CSS, as I see most of this styles are not used.

2017-11-01 14:15 UTC, Oksana098 commented on backend/create_database.py
> +    database_exists
yes but it should use only after three or more count imports

2017-11-01 14:27 UTC, serge30 commented on backend/create_database.py
> +    database_exists
hmm, can you point me to this rule please?

I'm talking about the PEP-8 (https://www.python.org/dev/peps/pep-0008/#id19):

> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

2017-11-01 14:33 UTC, NewIvanIvanov commented on .gitignore
> -flask
fixed

2017-11-01 14:46 UTC, NewIvanIvanov commented on backend/models/users.py
> +    def data_validataion(self):
this is server side validation

2017-11-01 15:10 UTC, serge30 commented on backend/models/users.py
> +    def data_validataion(self):
WTForms provides server side validation too.

2017-11-01 18:18 UTC, andrewRv commented on backend/migrations.py
> +from manage import *
If you move the code into manage.py there will be an error "Circular import".

2017-11-01 18:48 UTC, serge30 commented on backend/migrations.py
> +from manage import *
yes, but you can avoid it by adding `from models import users, issues` line at the bottom of `manage.py` script, after `db` variable initialization and before `if __name__ == '__main__':` line. Yes, it's violates PEP8, but it's the only option.

2017-11-01 18:49 UTC, andrewRv commented on backend/migrations.py
> +from manage import *
ok

2017-11-03 10:27 UTC, serge30 approved these changes

2017-11-03 10:28 UTC, merged